imageRegistry: docker.io

server:
  port: 7002
  broadcastUri: null
  broadcastPgsql: true
  uvicornWorkers: 4
  replicas: 1

client:
  port: 7000
  opaPort: 8181
  replicas: 1
  uvicornWorkers: 1

env:
  OPAL_DATA_CONFIG_SOURCES:
    config:
      entries: []
  OPAL_POLICY_REPO_URL: "https://github.com/authorizon/opal-example-policy-repo"
  OPAL_POLICY_REPO_POLLING_INTERVAL: 30