imagePullPolicy: IfNotPresent
imageRegistry: docker.io

server:
  image:
    path: /authorizon/
    name: opal-server
  port: 7002
  policyRepoUrl: "https://github.com/authorizon/opal-example-policy-repo"
  pollingInterval: 30
  dataConfigSources:
    config:
      entries: []
  broadcastUri: null
  broadcastPgsql: true
  uvicornWorkers: 4
  replicas: 1

client:
  image:
    path: /authorizon/
    name: opal-client
  port: 7000
  opaPort: 8181
  replicas: 1
