apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Release.Name }}-env"
data:
  {{- if .Values.env }}
  {{- range $key, $value := .Values.env }}
    {{- if eq $key "OPAL_DATA_CONFIG_SOURCES" }}
      {{ $key | quote }}: {{ $value | toJson | squote }}
    {{- else }}
      {{ $key | quote }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
  {{- end }}
