{{- if .Values.server.policyRepoSshKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "opal.envSecretsName" . }}
type: Opaque
data:
  OPAL_POLICY_REPO_SSH_KEY: {{ .Values.server.policyRepoSshKey | replace "\n" "_" | b64enc }}
{{- end }}
