name: CI

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  ci_job:
    name: Continous integration
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: azure/setup-helm@v1
        with:
          version: "3.3.4"
      - name: helm lint
        run: |
          jq --version
          ./test/linter/test.sh
      - name: start k8s with k3d
        uses: AbsaOSS/k3d-action@v1.4.0
        with:
          cluster-name: "opal"
          use-default-registry: false
          args: >-
            --config ./test/e2e/k3d.yaml
      - name: deploy opal
        run: |
          ./test/e2e/deploy.sh
      - name: e2e test
        run: |
          ./test/e2e/test.sh
